#!/bin/sh

set -e

if [ "$1" = "purge"  ]; then
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_input high solr3/purgeindexfiles || true
        db_go || true
        db_get solr3/purgeindexfiles || true
        if [ "$RET" = "true" ]; then
            rm -rf /var/lib/solr3
        fi
    else
        rm -rf /var/lib/solr3
    fi
fi

#DEBHELPER#
