#!/bin/sh

set -e

case "$1" in
    remove)
        rm -f /etc/tomcat7/policy.d/05solr.policy
    	if [ -x /usr/sbin/invoke-rc.d ]; then
    	    invoke-rc.d tomcat7 restart || true
    	fi
    ;;
    upgrade|purge|failed-upgrade|abort-install|abort-upgrade|disappear)
	    # do nothing
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;

esac

#DEBHELPER#
